#!/bin/bash

# Process environment variables
if [[ "$TRAVIS_PULL_REQUEST" =~ ^[0-9]+$ ]]; then
  echo "Building pull request #$TRAVIS_PULL_REQUEST, will skip deploy" >&2

  NO_DEPLOY=true
  unset GH_TOKEN TRAVIS_GITHUB_TOKEN
fi

unset DEPLOY # should not appear in environment
while [ $# -ne 0 ]; do
  case $1 in
    --deploy)
      [ -z "$NO_DEPLOY" ] && DEPLOY=true
      ;;
    *)
      # unknown option
      ;;
  esac
  shift
done

function force-fetch {
  if [[ -d "$1/.git" ]]; then
    echo "Force-fetching $1..."
    bash -c "cd '$1' && git checkout -q master && git fetch -q && git reset --hard -q origin/master"
  else
    rm -rf "$1"
    git clone --depth 1 -q -b master "$2" "$1"
  fi
}

: ${TRAVIS_REPO_SLUG:=Charcoal-SE/charcoal-se.github.io}
if [ -z "$DEPLOY" ]; then
  echo "Not in deploy mode, not pushing changes."
  force-fetch _site "https://github.com/${TRAVIS_REPO_SLUG}" &
elif [ -z "$GH_TOKEN" ]; then
  echo "No token provided. Cannot push changes."
  force-fetch _site "https://github.com/${TRAVIS_REPO_SLUG}" &
else
  force-fetch _site "https://$GH_TOKEN@github.com/${TRAVIS_REPO_SLUG}" &
fi
force-fetch ms "https://github.com/Charcoal-SE/metasmoke.wiki" &
force-fetch smokey "https://github.com/Charcoal-SE/SmokeDetector.wiki" &
wait

for file in **/Home.md; do
  mv "$file" "$(dirname "$file")/index.md"
done

script/add-front-matter.rb ms/** smokey/** &
script/create-data-files.rb &
wait

self_time=$(date -d $(git log -1 --pretty=%cI) +%s)
ms_wiki_time=$(date -d $(git -C ./ms log -1 --pretty=%cI) +%s)
smokey_wiki_time=$(date -d $(git -C ./smokey log -1 --pretty=%cI) +%s)

echo
test $self_time -ge $ms_wiki_time -a $self_time -ge $smokey_wiki_time && echo -ne "\e[32;1m"
git             log -1 --pretty="Website commit:     [%h] %s"
echo -ne "\e[0m"
test $ms_wiki_time -ge $self_time -a $ms_wiki_time -ge $smokey_wiki_time && echo -ne "\e[32;1m"
git -C ./ms     log -1 --pretty="MS wiki commit:     [%h] %s"
echo -ne "\e[0m"
test $smokey_wiki_time -ge $self_time -a $smokey_wiki_time -ge $ms_wiki_time && echo -ne "\e[32;1m"
git -C ./smokey log -1 --pretty="Smokey wiki commit: [%h] %s"
echo -ne "\e[0m"
echo

COMMIT_INFO="$(git log -1 --pretty="[%h] %an: %B")"

rm -r _site/assets # remove old assets

export PAGES_ENV=dotcom # GitHub.com

if [ -n "$DEPLOY" ]; then
  export JEKYLL_ENV=production

  if [ -n "$ALGOLIA_API_KEY" ]; then
    bundle exec jekyll algolia push --trace &
  fi
  bundle exec jekyll build --incremental --profile --trace &
  wait
else
  bundle exec jekyll build --incremental --profile --trace
fi

pushd _site &>/dev/null  # _site
pushd assets &>/dev/null  # _site/assets
mkdir -p css images

for file in branding*.css; do
  cp "$file" css/branding.css
done
for file in charcoal*.png; do
  cp "$file" images/charcoal.png
done

popd &>/dev/null  # OLDPWD=_site/assets/; PWD=_site/

if [ -n "$DEPLOY" ]; then
  :> .nojekyll
  git add --all
  git config --global push.default tracking
  ORIGINAL_NAME="$(git config --get user.name)"
  ORIGINAL_EMAIL="$(git config --get user.email)"
  git config user.name "SmokeDetector"
  git config user.email "smokey@erwaysoftware.com"

  if [ -n "$TRAVIS_COMMIT" ]; then
    git commit --allow-empty -q \
      -m "Auto deploy from Travis CI build ${TRAVIS_BUILD_NUMBER:-<unknown>}" \
      -m "${COMMIT_INFO}"
    git push -q
  else
    git commit --allow-empty -q \
      -m "Auto deploy from Travis CI build ${TRAVIS_BUILD_NUMBER:-<unknown>}" \
      -m "${COMMIT_INFO}"
    echo -e "Skipped push to GitHub Pages."
  fi

  git config user.name "$ORIGINAL_NAME"
  git config user.email "$ORIGINAL_EMAIL"
fi

popd &>/dev/null  # OLDPWD=_site/; PWD=(git root)
