#!/bin/bash

for i in "$@"
do
  case $i in
    --deploy)
      DEPLOY=YES
      shift # past argument with no value
      ;;
    *)
      # unknown option
      ;;
  esac
done

if [[ $DEPLOY ]]; then
  bundle install --deployment
else
  bundle install
fi
