#!/bin/bash

while [ $# -ne 0 ]; do
  case $1 in
    --deploy)
      DEPLOY=YES
      ;;
    *)
      # unknown option
      ;;
  esac
  shift
done

bundle config set --local path 'vendor/bundle'
bundle install
