name: build

on:
  push:
    branches: [site]
  repository_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Bundler cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |-
            ${{ runner.os }}-bundler-
      - name: Install dependencies
        run: bash script/install --deploy
      - name: Build
        run: bash script/build --deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
