name: build

on:
  push:
    branches: [site]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Bundler cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |-
            ${{ runner.os }}-bundler-
            ${{ runner.os }}-
      - name: Install dependencies
        run: bash script/install --deploy
      - name: Build
        run: bash script/build --deploy
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JEKYLL_ENV: production
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAGES_REPO_NWO: ${{ env.GITHUB_REPOSITORY }}
